apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
  #  repoURL: https://github.com/bakavets/k8s-lessons.git  # Can point to either a Helm chart repo or a git repo.
  #  targetRevision: master  # For Helm, this refers to the chart version.
    repoURL: https://github.com/pauldon2/k8s.git
    targetRevision: HEAD  # For Helm, this refers to the chart version.
    path: argocd/demo-dev/applications  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true
